# Generated by Django 3.1.6 on 2021-03-26 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('starting_date', models.DateField()),
                ('course_fees', models.IntegerField()),
                ('batch_status', models.CharField(choices=[('2', 'progress'), ('1', 'yettobegin'), ('3', 'completed')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=120, unique=True)),
                ('course_duration', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('enquiry_id', models.CharField(editable=False, max_length=120, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('qualification', models.CharField(max_length=100)),
                ('collegename', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('followupdate', models.DateField()),
                ('admission_status', models.CharField(choices=[('2', 'notadmitted'), ('1', 'admitted')], max_length=120)),
                ('batch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_automation.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=120, unique=True)),
                ('coursefees', models.IntegerField()),
                ('date', models.DateField()),
                ('batch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_automation.batch')),
                ('enquiry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_automation.enquiry')),
            ],
        ),
        migrations.CreateModel(
            name='Feepayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('admission_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_automation.registration')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_automation.course'),
        ),
    ]
