# Generated by Django 3.1.6 on 2021-03-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='course_image',
            field=models.ImageField(null=True, upload_to='image1'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_status',
            field=models.CharField(choices=[('1', 'yettobegin'), ('2', 'progress'), ('3', 'completed')], max_length=120),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='admission_status',
            field=models.CharField(choices=[('1', 'admitted'), ('2', 'notadmitted')], max_length=120),
        ),
    ]
