# Generated by Django 3.1.6 on 2021-03-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_automation', '0002_auto_20210327_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_status',
            field=models.CharField(choices=[('2', 'progress'), ('1', 'yettobegin'), ('3', 'completed')], max_length=120),
        ),
        migrations.AlterField(
            model_name='batch',
            name='course_image',
            field=models.FileField(null=True, upload_to='image1'),
        ),
    ]
