# Generated by Django 3.1.6 on 2021-03-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_automation', '0004_auto_20210327_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_status',
            field=models.CharField(choices=[('2', 'progress'), ('3', 'completed'), ('1', 'yettobegin')], max_length=120),
        ),
        migrations.AlterField(
            model_name='batch',
            name='course_image',
            field=models.ImageField(upload_to='image1'),
        ),
    ]
