# Generated by Django 3.1.6 on 2021-03-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_automation', '0007_auto_20210329_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_status',
            field=models.CharField(choices=[('yettobegin', 'yettobegin'), ('completed', 'completed'), ('progress', 'progress')], max_length=120),
        ),
    ]
