# Generated by Django 3.1.6 on 2021-03-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_automation', '0008_auto_20210329_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_status',
            field=models.CharField(choices=[('completed', 'completed'), ('yettobegin', 'yettobegin'), ('progress', 'progress')], max_length=120),
        ),
    ]
