# Generated by Django 3.1.6 on 2021-03-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_automation', '0011_auto_20210330_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_id',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
    ]
