# Generated by Django 3.1.6 on 2021-03-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_automation', '0012_auto_20210330_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_status',
            field=models.CharField(choices=[('completed', 'completed'), ('yettobegin', 'yettobegin'), ('progress', 'progress')], max_length=120),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='admission_status',
            field=models.CharField(choices=[('admitted', 'admitted'), ('notadmitted', 'notadmitted')], max_length=120),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_id',
            field=models.CharField(editable=False, max_length=120, primary_key=True, serialize=False),
        ),
    ]
