# Generated by Django 3.1.6 on 2021-03-31 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_automation', '0020_auto_20210331_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_status',
            field=models.CharField(choices=[('completed', 'completed'), ('progress', 'progress'), ('yettobegin', 'yettobegin')], max_length=120),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='admission_status',
            field=models.CharField(choices=[('notadmitted', 'notadmitted'), ('admitted', 'admitted')], max_length=120),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(max_length=120),
        ),
    ]
