# Generated by Django 3.1.6 on 2021-04-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_automation', '0024_auto_20210403_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_status',
            field=models.CharField(choices=[('yettobegin', 'yettobegin'), ('completed', 'completed'), ('progress', 'progress')], max_length=120),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='admission_status',
            field=models.CharField(choices=[('callback', 'callback'), ('admitted', 'admitted'), ('notadmitted', 'notadmitted')], max_length=120),
        ),
    ]
